libc: 	* aclocal.m4 (ACX_PKGVERSION, ACX_BUGURL): Define. 	* configure.in: Use ACX_PKGVERSION and ACX_BUGURL. 	* configure: Regenerate. 	* config.h.in (PKGVERSION, REPORT_BUGS_TO): Undefine. 	* config.make.in (PKGVERSION, REPORT_BUGS_TO): Define. 	* catgets/gencat.c (more_help): Use REPORT_BUGS_TO. 	(print_version): Use PKGVERSION. 	* csu/version.c (banner): Use PKGVERSION and REPORT_BUGS_TO. 	* debug/Makefile ($(objpfx)catchsegv, $(objpfx)xtrace): Also 	substitute PKGVERSION and REPORT_BUGS_TO. 	* debug/catchsegv.sh: Use PKGVERSION and REPORT_BUGS_TO. 	* debug/pcprofiledump.c (print_version, 	argp_program_version_hook): New. 	(more_help): Use REPORT_BUGS_TO. 	* debug/xtrace.sh: Use PKGVERSION and REPORT_BUGS_TO. 	* elf/Makefile (common-ldd-rewrite): Also substitute PKGVERSION 	and REPORT_BUGS_TO. 	* elf/dl-close.c (_dl_close_worker): Use REPORT_BUGS_TO. 	* elf/ldconfig.c (doc): Use REPORT_BUGS_TO. 	(print_version): Use PKGVERSION. 	* elf/ldd.bash.in: Use PKGVERSION and REPORT_BUGS_TO. 	* elf/sln.c (usage): New. 	(main): Support --help and --version. 	* elf/sprof.c (doc): Use REPORT_BUGS_TO. 	(print_version): Use PKGVERSION. 	* iconv/iconv_prog.c (more_help): Use REPORT_BUGS_TO. 	(print_version): Use PKGVERSION. 	* iconv/iconvconfig.c (more_help): Use REPORT_BUGS_TO. 	(print_version): Use PKGVERSION. 	* locale/programs/locale.c (doc): Use REPORT_BUGS_TO. 	(print_version): Use PKGVERSION. 	* locale/programs/localedef.c (more_help): Use REPORT_BUGS_TO. 	(print_version): Use PKGVERSION. 	* login/programs/pt_chown.c 	* malloc/Makefile ($(objpfx)mtrace, $(objpfx)memusage): Also 	substitute PKGVERSION and REPORT_BUGS_TO. 	* malloc/memusage.sh: Use PKGVERSION and REPORT_BUGS_TO. 	* malloc/memusagestat.c (print_version, 	argp_program_version_hook): New. 	(more_help): Use REPORT_BUGS_TO. 	* malloc/mtrace.pl: Use PKGVERSION and REPORT_BUGS_TO. 	* manual/Makefile (libc.dvi, libc.pdf, libc.info, 	libc/index.html): Depend on pkgvers.texi. 	(pkgvers.texi, stamp-pkgvers): New. 	* manual/install.texi: Adjust bug database description.  Use 	REPORT_BUGS_TO. 	* manual/libc.texinfo: Include pkgvers.texi.  Use PKGVERSION. 	* nscd/nscd.c (doc): Use REPORT_BUGS_TO. 	(print_version): Use PKGVERSION. 	* nss/getent.c (doc): Use REPORT_BUGS_TO. 	(print_version): Use PKGVERSION. 	* nss/makedb.c (more_help): Use REPORT_BUGS_TO. 	(print_version): Use PKGVERSION. 	* posix/getconf.c (main): Send --version output to stdout.  Use 	PKGVERSION.  Support --help. 	* sunrpc/proto.h (REPORT_BUGS_TO, PKGVERSION): Define for 	cross-rpcgen. 	* sunrpc/rpc_main.c (usage, options_usage): Take STREAM and STATUS 	arguments.  All callers changed.  Use REPORT_BUGS_TO 	(print_version): New. 	(parseargs): Support --help and --version. 	* sunrpc/rpcinfo.c (usage): Take STREAM argument.  All callers 	changed.  Use REPORT_BUGS_TO. 	(print_version): New. 	(main): Use getopt_long.  Support --help and --version. 	* sysdeps/unix/sysv/linux/lddlibc4.c (main): Support --help and 	--version. 	* timezone/Makefile: Use -DCROSS_ZIC for cross-zic. 	($(objpfx)tzselect): Also substitute PKGVERSION and 	REPORT_BUGS_TO. 	* timezone/tzselect.ksh: Support --help and --version. 	* timezone/zdump.c (usage): New. 	(main): Use it.  Support --help.  Print program name and 	PKGVERSION in --version output. 	* timezone/zic.c (usage): Take STREAM and STATUS arguments.  All 	callers changed.  Use REPORT_BUGS_TO. 	(main): Support --help.  Print program name and PKGVERSION in 	--version output.
localedef:
	* configure.ac: Support --with-pkgversion and --with-bugurl.
	* configure, config.h.in: Regenerate.


git-svn-id: http://eglibc.org/svn/trunk/localedef@7026 7b3dc134-2b1b-0410-93df-9e9f96275f8d

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -308,7 +308,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT LN_S CPP EGREP LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT LN_S CPP EGREP PKGVERSION REPORT_BUGS_TO REPORT_BUGS_TEXI LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -845,6 +845,8 @@ Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
   --with-glibc=PATH       specify location of glibc sources
+  --with-pkgversion=PKG   Use PKG in the version string in place of "EGLIBC"
+  --with-bugurl=URL       Direct users to URL to report a bug
 
 Some influential environment variables:
   CC          C compiler command
@@ -4920,6 +4922,70 @@ _ACEOF
 fi
 
 
+# These two macros are taken from GCC's config/acx.m4.
+
+
+
+
+
+# Check whether --with-pkgversion or --without-pkgversion was given.
+if test "${with_pkgversion+set}" = set; then
+  withval="$with_pkgversion"
+  case "$withval" in
+      yes) { { echo "$as_me:$LINENO: error: package version not specified" >&5
+echo "$as_me: error: package version not specified" >&2;}
+   { (exit 1); exit 1; }; } ;;
+      no)  PKGVERSION= ;;
+      *)   PKGVERSION="($withval) " ;;
+     esac
+else
+  PKGVERSION="(EGLIBC) "
+
+fi;
+
+
+
+
+# Check whether --with-bugurl or --without-bugurl was given.
+if test "${with_bugurl+set}" = set; then
+  withval="$with_bugurl"
+  case "$withval" in
+      yes) { { echo "$as_me:$LINENO: error: bug URL not specified" >&5
+echo "$as_me: error: bug URL not specified" >&2;}
+   { (exit 1); exit 1; }; } ;;
+      no)  BUGURL=
+	   ;;
+      *)   BUGURL="$withval"
+	   ;;
+     esac
+else
+  BUGURL="http://www.eglibc.org/issues/"
+
+fi;
+  case ${BUGURL} in
+  "")
+    REPORT_BUGS_TO=
+    REPORT_BUGS_TEXI=
+    ;;
+  *)
+    REPORT_BUGS_TO="<$BUGURL>"
+    REPORT_BUGS_TEXI=@uref{`echo "$BUGURL" | sed 's/@/@@/g'`}
+    ;;
+  esac;
+
+
+
+
+cat >>confdefs.h <<_ACEOF
+#define PKGVERSION "$PKGVERSION"
+_ACEOF
+
+
+cat >>confdefs.h <<_ACEOF
+#define REPORT_BUGS_TO "$REPORT_BUGS_TO"
+_ACEOF
+
+
 rm -f glibc && $LN_S $with_glibc glibc
 case $build_os in
   solaris*)
@@ -5552,6 +5618,9 @@ s,@OBJEXT@,$OBJEXT,;t t
 s,@LN_S@,$LN_S,;t t
 s,@CPP@,$CPP,;t t
 s,@EGREP@,$EGREP,;t t
+s,@PKGVERSION@,$PKGVERSION,;t t
+s,@REPORT_BUGS_TO@,$REPORT_BUGS_TO,;t t
+s,@REPORT_BUGS_TEXI@,$REPORT_BUGS_TEXI,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
